server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.zh.pojo
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名
logging:
  level:
    com.zh: debug
